[package]
name = "spl-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["cargo", "derive"] }
nom = "8.0.0"
colored = "3.0.0"
anyhow = "1.0.98"
rstest = "0.25.0"
regex = "1.11.1"
dialoguer = "0.11.0"
bitvec = "1.0.1"